export const LOAD_BREAKING_NEWS = "LOAD_BREAKING_NEWS";
export const LOAD_EVERYTHING_NEWS = "LOAD_EVERYTHING_NEWS";
export const SAVE_CATEGORIES = "SAVE_CATEGORIES";
export const LOAD_INTERESTS = "LOAD_INTERESTS";
